version: '3.7'
services:
        nginx:
                image: nginx
                ports:
                        #Port's configure
                        #expose | container
                        - "8080:80"
